#!/bin/bash

export AGENT_NAME="pi-bubble"
export AGENT_CLI="pi"
export AGENT_YOLO_FLAG=""
export AGENT_CONTINUE_FLAG="--continue"

EXTRA_BWRAP_ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help) exec "$(dirname "$0")/bubble-run" --help ;;
        --) shift; break ;;
        *) EXTRA_BWRAP_ARGS+=("$1"); shift ;;
    esac
done

ALLOW_RW=(
  "$HOME/.pi"
  "$HOME/.agents"
)

ALLOW_RO=(
)

BANNED=(
)

ALLOW_RW_ARGS=()
for item in "${ALLOW_RW[@]}"; do
    ALLOW_RW_ARGS+=(--bind "$item" "$item")
done

ALLOW_RO_ARGS=()
for item in "${ALLOW_RO[@]}"; do
    ALLOW_RO_ARGS+=(--ro-bind "$item" "$item")
done

BANNED_ARGS=()
for item in "${BANNED[@]}"; do
    BANNED_ARGS+=(--ro-bind /dev/null "$PWD/$item")
done

exec "$(dirname "$0")/bubble-run" \
     "${ALLOW_RW_ARGS[@]}" \
     "${ALLOW_RO_ARGS[@]}" \
     "${BANNED_ARGS[@]}" \
     -- \
     "$(command -v pi)" --offline "$@"
